Radix/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Sensores.urls', namespace='Sensores'))
]

Sensores/urls.py
from django.urls import path, include
from . import views
from .views import LeituraSensor, Homesensores, PesquisaSensor

app_name = 'Sensores'

urlpatterns = [
    path('api/Leitura_Json', views.dados_json, name='dados_json'),
    path('api/Leitura_CSV', views.dados_csv, name='dados_csv'),
    #path('leitura/<str:id_sensor>', LeituraSensor.as_view(), name='leitura_sensor'),
    path('leitura/<int:pk>', LeituraSensor.as_view(), name='leitura_sensor'),
    path('', Homesensores.as_view(),name='sensores'),
    path('pesquisa', PesquisaSensor.as_view(),name= 'pesquisa_sensor')
]

Sensores/models.py
from django.db import models

# Create your models here.


class Sensor(models.Model):
    id_sensor = models.CharField(max_length = 8, unique=True)
    nome = models.CharField(max_length = 50)

    def __str__(self):
        return self.nome
    
    @classmethod
    def sensor_existe(cls, equipmentId):

        return cls.objects.filter(id_sensor=equipmentId).exists()
    


    def criar_Leitura(self, timestamp, value):
        Leitura.objects.create(sensor = self, timestamp = timestamp, valor = value)
        return None



class Leitura(models.Model):
    sensor = models.ForeignKey(Sensor, related_name='leitura' ,on_delete= models.CASCADE)
    timestamp = models.DateTimeField()
    valor = models.FloatField()

    class Meta:
        unique_together = (('sensor','timestamp'),)
    
    def __str__(self):
        return 'Leitura ' + str(self.timestamp)[:19] + ' - Sensor ' + self.sensor.nome
    
    

Sensores/views.py
from django.views.generic import ListView, DetailView
from .models import Sensor
import csv, json
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt
from django.utils import timezone
from datetime import timedelta
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
import io, base64
from .validators import valida_json, valida_arquivo, valida_equipmentId, valida_timestamp, valida_value

# Create your views here.

@csrf_exempt
def dados_json(request):

    if request.method != 'POST':
        return JsonResponse({"erro": 'API só recebe requisições do tipo POST'})

    dados_sensor = json.loads(request.body)
    
    try:
        equipmentId, timestamp, value = valida_json(dados_sensor)
    
    except Exception as erro:
        msg = 'Json nao foi inserido. '
        msg += str(erro)
        return JsonResponse({"erros": msg})
    
    try:
        valida_equipmentId(equipmentId)  
        timestamp_recebido = timestamp
        timestamp = valida_timestamp(timestamp_recebido)
        value = valida_value(value)
        
    except Exception as erro:
        msg = str("Json nao foi inserido.")
        erro = str(erro)
        msg += erro
        return JsonResponse({"erros": msg})


    #verifica se sensor ja existe no BD
    if Sensor.sensor_existe(equipmentId) == False:

        #Construtor padrão do Django. Instancia novo objeto da classe Sensor e salva no BD.
        name = 'testex'+ equipmentId 
        sensor = Sensor.objects.create(id_sensor = equipmentId, nome = name )
            
    sensor = Sensor.objects.get(id_sensor = equipmentId)

    try:
        sensor.criar_Leitura(timestamp, value) 
    
    except:
        return JsonResponse({"codigo": 400, "erro": f"Json NAO foi inserido. Ja existe uma leitura associada a:{equipmentId, timestamp_recebido}. Um mesmo sensor NAO pode ter mais de uma leitura em um mesmo instante de tempo."})
            
    return JsonResponse({"codigo":201, "mensagem":"Json recebido com sucesso"})





@csrf_exempt
def dados_csv(request):

    if request.method != 'POST':
        return JsonResponse({"erros": 'API só recebe requisições do tipo POST'})
    
    erros = []  
    
    try:
        arquivo = valida_arquivo(request.body)
    
    except Exception as erro:
        erro = str(erro)
        erros.append(erro)
        return JsonResponse({"erros": erros})

    
    arquivo_csv = list(csv.reader(arquivo))
    
    #acha posição do cabeçalho do arquivo_csv e soma 1, pois queremos os valores e nao o proprio cabeçalho
    try:
        posicao_cabecalho = arquivo_csv.index(['equipmentId;timestamp;value']) + 1
    
    except:
        erros.append({"codigo": 400, "mensagem": "header do csv, ou seja, os nomes das colunas estão errados ou na ordem incorreta"})
        return JsonResponse({"erros": erros})
    
    for linha in arquivo_csv[posicao_cabecalho:]:
        
        #condiçao identificada que, apos o cabeçalho, a lista vazia representa o fim do arquivo
        if linha == []:
            break
            
        
        equipmentId, timestamp, value = linha[0].split(';')
        
        try:
            valida_equipmentId(equipmentId)  
            timestamp_recebido = timestamp
            timestamp = valida_timestamp(timestamp)
            value = valida_value(value)
        
        except Exception as erro:
            msg = f"A linha:{str(linha)} NAO foi inserida. "
            msg += str(erro)
            erros.append(msg)
            continue

        if Sensor.sensor_existe(equipmentId) == False:
            name = 'testex'+ equipmentId
            sensor = Sensor.objects.create(id_sensor = equipmentId, nome = name)
        
        else:
            sensor = Sensor.objects.get(id_sensor = equipmentId)
        
        try:
            sensor.criar_Leitura(timestamp, value)
        
        except:
            erros.append({"codigo": 400, "mensagem": f"A linha:{str(linha)} NAO foi inserida. Pois ja existe uma leitura associada a:{equipmentId, timestamp_recebido}. Um mesmo sensor NAO pode ter mais de uma leitura em um mesmo instante de tempo."})

    
    mensagem = 'recebi o arquivo csv com sucesso'
    
    if len(erros) > 0:
        return JsonResponse({"mensagem": mensagem, "erros": erros})
    
    else:
        return JsonResponse({"codigo":201, "mensagem": mensagem})        


class Homesensores(ListView):
    template_name = 'sensores.html'
    model = Sensor

    


class LeituraSensor(DetailView):
    template_name = 'detalhes_sensor.html'
    model = Sensor

    def constroi_grafico(self, tempo):
        
        sensor = self.get_object()
        agora = timezone.now().astimezone(timezone.get_current_timezone())
        limite_tempo = agora - timedelta(hours=tempo)
        leituras = sensor.leitura.filter(timestamp__gte=limite_tempo).order_by("timestamp")
        
        fig, ax = plt.subplots()
        x, y = list(), list()
        for leitura in leituras:
           x.append(str(leitura.timestamp)[:16])
           y.append(leitura.valor)
        
        ax.plot(x, y)
        ax.set_xlabel('Timestamp')
        ax.set_ylabel('Valor')
        ax.set_title('Gráfico de Leituras')
        plt.xticks(rotation=90)

        buffer = io.BytesIO()
        plt.savefig(buffer, format='png')
        buffer.seek(0)
        image_png = buffer.getvalue()
        buffer.close()

        grafico = base64.b64encode(image_png).decode('utf-8')
        
        return grafico

    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        
        #obtemos o parametro de url que esta sendo passado            
        tempo = int(self.request.GET.get('horas'))

        #geramos o grafico em uma funçao propria para isso, criada acima 
        grafico = self.constroi_grafico(tempo)

        #adicionamos o grafico gerado ao dicionario context, para podermos utiliza-lo no nosso template
        context['grafico'] = grafico
    
        return context
    

class PesquisaSensor(ListView):
    template_name = 'pesquisa_sensor.html'
    model = Sensor

    def get_queryset(self):
        
        #parametro 'query' porque no pesquisa_sensor.html o formulario foi criado  com esse parametro
        termo_pesquisa = self.request.GET.get('query')
        if termo_pesquisa != '':
            object_list = self.model.objects.filter(id_sensor__contains = termo_pesquisa)
            return object_list
        
        else:
            return None

Sensores/templates/detalhes_sensor.html
{% extends 'base.html' %}

{% block title %}
    Detalhes_Sensor
{% endblock%}


{% block content %}

<div class="py-10 px-28 flex justify-between" >

<a href="{% url 'Sensores:leitura_sensor' sensor.pk %}?horas=24"><button type="button" class="btn btn-primary">24 horas</button></a>
<a href="{% url 'Sensores:leitura_sensor' sensor.pk %}?horas=48"><button type="button" class="btn btn-primary">48 horas</button></a>
<a href="{% url 'Sensores:leitura_sensor' sensor.pk %}?horas=168"><button type="button" class="btn btn-primary">1 semana</button></a>
<a href="{% url 'Sensores:leitura_sensor' sensor.pk %}?horas=720"><button type="button" class="btn btn-primary">1 mês</button></a>
</div>

<div>
    <h1></h1>
</div>
<div class="py-28 text-center flex items-center flex-col">
    <img src="data:image/png;base64,{{ grafico }}" alt="Meu Gráfico" width="800" height="600">
</div>



{% endblock %}

Sensores/templates/pesquisa_sensor.html
{% extends 'base.html'%}

{% block title %}
    Pesquisa
{% endblock %}


{% block content %}
{% include 'navbar.html' %}

<main>

<section class='bg-primary_black flex justify-center py-32'>
    <div class="py-32 w-10/12 relative text-center" >
        <h2 class="text-gray-200 text-3xl font-medium">
            Resultados da Pesquisa
        </h2>
        
        {% if object_list|length < 1 %}
        <h2 class="p-32 text-gray-200 text-2xl font-bold">
            Não foram encontrados resultados para sua Pesquisa
        </h2>
        {% endif %}

        <div class="py-12 flex flex-wrap items-center min-w-full movie_lis">
            {% for sensor in object_list %}
            <div class="m-4 bg-blue-500 overflow-hidden flex-shrink-0 rounded-md cursor-pointer h-14 w-32 py-2">
                <a href="{% url 'Sensores:leitura_sensor' sensor.pk %}?horas=24"><button type="button" class="btn btn-primary">{{sensor.id_sensor}}</button></a>
            </div>
            {% endfor %}
        </div>
    </div>
</section>

</main>

{% endblock %}

Sensores/templates/sensores.html
{% extends 'base.html' %}


{% block title %}
    HomeSensores
{% endblock%}


{% block content %}
{% include 'navbar.html'%}



<div class="  md:py-0 text-gray-100 text-center flex items-center flex-col">
        
    <h1 class="py-32 font-semibold text-4xl md:text-5xl w-10/12 md:w-3/4 text-center"> 
        Valor Médio dos Sensores
    </h1>
</div>


<section id="section1" class="flex flex-nowrap items-center justify-center space-x-8">
    {% for sensor in object_list %}
      <div class="item h-64 w-3/4 m-4">
          <a href="{% url 'Sensores:leitura_sensor' sensor.pk  %}?horas=24">
            <p>{{sensor.id_sensor}}</p>
          </a>
      </div>
    {% endfor %}

{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        {%block title %}

        {% endblock %}
    </title>
    
    <script src="https://cdn.tailwindcss.com"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    
    {%block head %}

    {% endblock %}
</head>

<body class="bg-black text-white font-primary">
    
    {% block content %}
    
    {% endblock %}
</body>
</html>

templates/navbar.html
<nav class="w-full flex justify-between items-center py-3 px-4 fixed z-50">

    <div class="w-6/12 font-semibold  md:text-2xl w-10/12 md:w-3/4 ">
        <p>Sensores-Radix</p>

    </div>

    <div class="w-6/12 flex flex-nowrap justify-end">

        <div class="mr-2">
            <form method="get" action="{% url 'Sensores:pesquisa_sensor' %}">
                <input class="py-1 px-2 rounded-md text-black" placeholder="Pesquisar.." type="text" name="query">
                <!-- no input acima, tem uma classe q poderiamos adicionar, chamada 'value'. 
                    se quisessemos que, na pagina da pesquisa, o nome pelo qual pesquisamos aparecesse, ao inves do campo de pesquisa ser limpado
                    teriamos que adicionar no input acima: 'value = {{request.GET.query}}'-->
                <input type="submit" value="">
            </form>
        </div>
    
    </div>

</nav>